
 import Layout from '@/layout/index.vue'//外框
export const  Menu = 
[
	{
		"dataId":1,
		"mid":1,
		"menuName":"首页",
		"menuCode":"001",
		"menuPath":"/home",
		"owner":"user",
		"childMenus":null
	},
	{
		"dataId":2,
		"mid":1,
		"menuName":"日常办公",
		"menuCode":"002",
		"menuPath":"/office",
		"owner":"user",
		"childMenus":null
	},
	{
		"dataId":3,
		"mid":2,
		"menuName":"流程审批",
		"menuCode":"002",
		"menuPath":"/flow",
		"owner":"user",
		"childMenus":null
	},
	{
		"dataId":4,
		"mid":3,
		"menuName":"任务管理",
		"menuCode":"002",
		"menuPath":"/task",
		"owner":"user",
		"childMenus":null
	},
	{
		"dataId":5,
		"mid":4,
		"menuName":"资产管理",
		"menuCode":"002",
		"menuPath":"/property",
		"owner":"user",
		"childMenus":null
	},
	{
		"dataId":6,
		"mid":5,
		"menuName":"教务管理",
		"menuCode":"002",
		"menuPath":"/edu",
		"owner":"user",
		"childMenus":null
	},
	{
		"dataId":7,
		"mid":6,
		"menuName":"学工管理",
		"menuCode":"002",
		"menuPath":"/student",
		"owner":"user",
		"childMenus":null
	},
	{
	"dataId":8,
	"mid":7,
	"menuName":"智慧党建",
	"menuCode":"001",
	"menuPath":"/partyBuild",
	"owner":"user",
	"childMenus":[
			{
			"dataId":9,
			"mid":8,
			"menuName":"党员信息管理",
			"menuCode":"001",
			"menuPath":"/partyBuild/partyInfo",
			"parentId":1,
			"owner":"roll",
			"parentName":"智慧党建",
			"childMenus":[],
			"operations":[
				{"operationId":1,"operationName":"删除"}
			]
		},
		{
			"dataId":10,
			"mid":9,
			"menuName":"党费管理",
			"menuCode":"001",
			"menuPath":"/partyBuild/fee",
			"parentId":1,
			"owner":"roll",
			"parentName":"智慧党建",
			"childMenus":[],
			"operations":[
				{"operationId":1,"operationName":"删除"}
			]
		},
		{
			"dataId":11,
			"mid":10,
			"menuName":"组织管理",
			"menuCode":"001",
			"menuPath":"/partyBuild/org",
			"parentId":1,
			"owner":"roll",
			"parentName":"组织管理",
			"childMenus":[],
			"operations":[
				{"operationId":1,"operationName":"删除"}
			]
		},
		{
			"dataId":12,
			"mid":11,
			"menuName":"学习管理",
			"menuCode":"001",
			"menuPath":"/partyBuild/studyManage",
			"parentId":1,
			"owner":"roll",
			"parentName":"学习管理",
			"childMenus":[],
			"operations":[
				{"operationId":1,"operationName":"删除"}
			]
		},
		{
			"dataId":13,
			"mid":12,
			"menuName":"党建新闻",
			"menuCode":"001",
			"menuPath":"/partyBuild/news",
			"parentId":1,
			"owner":"roll",
			"parentName":"学习管理",
			"childMenus":[],
			"operations":[
				{"operationId":1,"operationName":"删除"}
			]
		},
		{
			"dataId":14,
			"mid":13,
			"menuName":"校务公开",
			"menuCode":"001",
			"menuPath":"/partyBuild/open",
			"parentId":1,
			"owner":"roll",
			"parentName":"校务公开",
			"childMenus":[],
			"operations":[
				{"operationId":1,"operationName":"删除"}
			]
		},
		{
			"dataId":15,
			"mid":14,
			"menuName":"党群活动",
			"menuCode":"001",
			"menuPath":"/partyBuild/partyGroup",
			"parentId":1,
			"owner":"roll",
			"parentName":"校务公开",
			"childMenus":[],
			"operations":[
				{"operationId":1,"operationName":"删除"}
			]
		},
		{
			"dataId":16,
			"mid":15,
			"menuName":"三会一课",
			"menuCode":"001",
			"menuPath":"/partyBuild/meeting",
			"parentId":1,
			"owner":"roll",
			"parentName":"校务公开",
			"childMenus":[],
			"operations":[
				{"operationId":1,"operationName":"删除"}
			]
		},
		{
			"dataId":17,
			"mid":16,
			"menuName":"党员学习",
			"menuCode":"001",
			"menuPath":"/partyBuild/partyStudy",
			"parentId":1,
			"owner":"roll",
			"parentName":"校务公开",
			"childMenus":[],
			"operations":[
				{"operationId":1,"operationName":"删除"}
			]
		},
		{
			"dataId":18,
			"mid":17,
			"menuName":"党风廉政",
			"menuCode":"001",
			"menuPath":"/partyBuild/partyStyle",
			"parentId":1,
			"owner":"roll",
			"parentName":"校务公开",
			"childMenus":[],
			"operations":[
				{"operationId":1,"operationName":"删除"}
			]
		},
		{
			"dataId":19,
			"mid":18,
			"menuName":"荣誉风采",
			"menuCode":"001",
			"menuPath":"/partyBuild/honor",
			"parentId":1,
			"owner":"roll",
			"parentName":"校务公开",
			"childMenus":[],
			"operations":[
				{"operationId":1,"operationName":"删除"}
			]
		},
	]
	}
		
	]
